version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLITE_FILE=db.sqlite3
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./db.sqlite3:/data/db.sqlite3
    command: ["tail", "-f", "/dev/null"]

# Postgresql kullanılacaksa alt kısım aktif edilmeli.
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: your_db_name
#       POSTGRES_USER: your_db_user
#       POSTGRES_PASSWORD: your_db_password

# volumes:
#   postgres_data:
